### ISSUE TITLE
Mariadb fails to start

### ISSUE THREAD

**Issue by james-nesbitt** [wunderkraut/image-fuzzy-alpine-mariadb#1]
The following error occurs when trying to run this image:

```
2016-05-06 05:45:58 7fb318858da8  InnoDB: Operating system error number 13 in a file operation.
InnoDB: The error means mysqld does not have the access rights to InnoDB: the directory.
```

If you chown the var/lib/mysql then it works fine:

```
$/> chown -R mysql:mysql /var/lib/mysql
```

**Comment by james-nesbitt** [comment]
This begs the question: should we make mysql run as app:app?  I think that it is not necessary.

**Comment by iler** [comment]
Me and @tharna discussed about this on Wednesday and actually we need to use app:app only on php, nginx and possibly drush images/containers. Mysql, varnish and memcached can be run with the default user:group. Do you agree?

**Comment by james-nesbitt** [comment]
agreed on user groups. Use app:app only on cases where file space is shared (from source)

**Comment by james-nesbitt** [comment]
original issue still needs solving
