### ISSUE TITLE
Maybe it doesn't make sense to instal_db before a custom my.cnf is installed

### ISSUE THREAD

**Issue by james-nesbitt** [wunderkraut/image-fuzzy-alpine-mariadb#3]
Extending this image with a new my.cnf, means that the mysql_install_db needs to be repeated (depending on the changes to the conf.)

Should we be installing in this image?  Should we accept a base image that does not itself produce a "running container"?

For example, [this image](https://github.com/wunderkraut/wundertools-image-fuzzy-mariadb) used to extend alpine-mariadb, but now just steals most of the Dockerfile, instead if re-creating the db.

**Comment by iler** [comment]
I don't see any reason why we could not have this image as a base image that does not itself produce a "running container". So let's drop the mysql_install_db from this image?

**Comment by james-nesbitt** [comment]
@iler I will submit a PR
